[project]
name = "make-your-own-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ollama>=0.6.2",
    "langchain>=0.1.0",
    "langchain-anthropic>=0.1.0",
    "sentence-transformers>=2.2.2",
    "pandas>=2.0.3",
    "faiss-cpu>=1.7.4",
    "ipython>=9.15.0",
    "langchain-ollama>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-text-splitters>=1.1.2",
]
